In [5]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [ ]:
kz = pd.read_csv("../data/kz.csv")
kz

,event_time,order_id,product_id,category_id,category_code,brand,price,user_id
0,2020-04-24 11:50:39 UTC,2294359932054536986,1515966223509089906,2.268105e+18,electronics.tablet,samsung,162.01,1.515916e+18
1,2020-04-24 11:50:39 UTC,2294359932054536986,1515966223509089906,2.268105e+18,electronics.tablet,samsung,162.01,1.515916e+18
2,2020-04-24 14:37:43 UTC,2294444024058086220,2273948319057183658,2.268105e+18,electronics.audio.headphone,huawei,77.52,1.515916e+18
3,2020-04-24 14:37:43 UTC,2294444024058086220,2273948319057183658,2.268105e+18,electronics.audio.headphone,huawei,77.52,1.515916e+18
4,2020-04-24 19:16:21 UTC,2294584263154074236,2273948316817424439,2.268105e+18,NaN,karcher,217.57,1.515916e+18
...,...,...,...,...,...,...,...,...
2633516,2020-11-21 10:10:01 UTC,2388440981134693942,1515966223526602848,2.268105e+18,electronics.smartphone,oppo,138.87,1.515916e+18
2633517,2020-11-21 10:10:13 UTC,2388440981134693943,1515966223509089282,2.268105e+18,electronics.smartphone,apple,418.96,1.515916e+18
2633518,2020-11-21 10:10:30 UTC,2388440981134693944,1515966223509089917,2.268105e+18,appliances.personal.scales,vitek,12.48,1.515916e+18
2633519,2020-11-21 10:10:30 UTC,2388440981134693944,2273948184839454837,2.268105e+18,NaN,moulinex,41.64,1.515916e+18
2633520,2020-11-21 10:10:30 UTC,2388440981134693944,1515966223509127566,2.268105e+18,appliances.kitchen.blender,redmond,53.22,1.515916e+18

In [18]:
kz.category_code.value_counts()

category_code
electronics.smartphone              357682
appliances.kitchen.refrigerators     77386
16.18                                72969
electronics.video.tv                 71711
computers.notebook                   71436
                                     ...
1388.87                                  1
752.29                                   1
240.72                                   1
71.74                                    1
62.01                                    1
Name: count, Length: 510, dtype: int64

In [25]:
(kz.category_code.value_counts(normalize=True) * 100).head(30)

category_code
electronics.smartphone                    17.695475
appliances.kitchen.refrigerators           3.828490
16.18                                      3.609970
electronics.video.tv                       3.547733
computers.notebook                         3.534128
appliances.environment.vacuum              3.288496
electronics.audio.headphone                3.273061
appliances.kitchen.kettle                  3.102875
appliances.kitchen.washer                  2.783084
furniture.kitchen.table                    2.756863
computers.peripherals.mouse                2.242546
57.87                                      2.233641
8.10                                       2.098184
9.26                                       2.023975
appliances.iron                            1.989246
29.63                                      1.918896
appliances.kitchen.blender                 1.815498
appliances.personal.scales                 1.628145
appliances.kitchen.hood                    1.589705
appliances.kitchen.microwave               1.447520
appliances.environment.air_conditioner     1.409030
stationery.battery                         1.233848
computers.network.router                   1.181456
6.94                                       1.018691
4.63                                       1.009390
appliances.kitchen.meat_grinder            0.983269
electronics.tablet                         0.969713
furniture.living_room.cabinet              0.843805
electronics.clocks                         0.790919
appliances.environment.water_heater        0.790672
Name: proportion, dtype: float64

In [12]:
mkt_amazon = pd.read_csv("../data/marketing_sample_for_amazon_com-ecommerce__20200101_20200131__10k_data.csv")

In [13]:
mkt_amazon.sample(5)

,Uniq Id,Product Name,Brand Name,Asin,Category,Upc Ean Code,List Price,Selling Price,Quantity,Model Number,About Product,Product Specification,Technical Details,Shipping Weight,Product Dimensions,Image,Variants,Sku,Product Url,Stock,Product Details,Dimensions,Color,Ingredients,Direction To Use,Is Amazon Seller,Size Quantity Variant,Product Description
3572,dd6beed921a0a78aeed1cdb42e4a78d2,Costume Sunglasses Sesame Street Bert Sun-Stac...,NaN,NaN,"Clothing, Shoes & Jewelry | Men | Accessories ...",878599411930,NaN,$10.50,NaN,sesame,All Sun-Staches Sunglasses provide 100% UV400 ...,Product Dimensions: 8 x 7 x 1 inches ;...,"Color:Bert ""Yes I do mind!"" Become Bert, the e...",0.3 ounces,8 x 7 x 1 inches 0.32 ounces,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/Costume-Sunglasses-Sesa...,NaN,https://www.amazon.com/Costume-Sunglasses-Sesa...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
2121,9a3631743134887e98b7feb2f4eb4e31,Ideal SNO Scapes Scene Creator Set Kids Outdoo...,NaN,NaN,Toys & Games | Arts & Crafts | Craft Kits | Pa...,NaN,NaN,$17.99,NaN,400220-2,Make sure this fits by entering your model num...,ProductDimensions:12x2.5x10.5inches|ItemWeight...,show up to 2 reviews by default Ideal Sno toys...,1.06 pounds,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,NaN,https://www.amazon.com/ideals-Sno-Scapes-Blue-...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
14,1ecccb43e0f5c0162218371916ffa553,C&D Visionary DC Comic Originals Flash Logo St...,NaN,NaN,Toys & Games | Arts & Crafts | Craft Kits,NaN,NaN,$4.99,NaN,S-DC-0140,Make sure this fits by entering your model num...,ProductDimensions:5x0x4inches|ItemWeight:0.16o...,show up to 2 reviews by default C&D Visionary ...,0.16 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,NaN,https://www.amazon.com/Visionary-Comic-Origina...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
3473,dfddf9f85384157764f6a9bf41b86706,Rubie's Star Wars Classic Luke Skywalker Child...,NaN,NaN,Toys & Games | Dress Up & Pretend Play | Costumes,NaN,NaN,$24.49,NaN,883159_L,Make sure this fits by entering your model num...,ProductDimensions:12x10x3inches|ItemWeight:9.1...,Go to your orders and start the return Select ...,12.8 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/Rubies-Classic-Childs-S...,NaN,https://www.amazon.com/Rubies-Classic-Childs-S...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
3139,a6e7147738c1dc029c160d6f519a2661,Frozen Magic Touch Guitar - Features Songs - L...,NaN,NaN,Toys & Games | Dress Up & Pretend Play | Prete...,NaN,NaN,$22.99,NaN,204782-1,Make sure this fits by entering your model num...,ProductDimensions:20x2.5x9.5inches|ItemWeight:...,Go to your orders and start the return Select ...,2.1 pounds,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,NaN,https://www.amazon.com/Frozen-Guitar-SummerFor...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN

In [9]:
mkt_amazon["About Product"][0]

"Make sure this fits by entering your model number. | RESPONSIVE FLEX: The Crossbow features a bamboo core encased in triaxial fiberglass and HD plastic for a responsive flex pattern that’s second to none. Pumping & carving have never been so satisfying! Flex 2 is recommended for people 120 to 170 pounds. | COREFLEX TECH: CoreFlex construction is water resistant, impact resistant, scratch resistant and has a flex like you won’t believe. These boards combine fiberglass, epoxy, HD plastic and bamboo to create a perfect blend of performance and strength. | INSPIRED BY THE NORTHWEST: Our founding ideal is chasing adventure & riding the best boards possible, inspired by the hills, waves, beaches & mountains all around our headquarters in the Northwest | BEST IN THE WORLD: DB was founded out of sheer love of longboarding with a mission to create the best custom longboards in the world, to do it sustainably, & to treat customers & employees like family | BEYOND COMPARE: Try our skateboards & accessories if you've tried similar products by Sector 9, Landyachtz, Arbor, Loaded, Globe, Orangatang, Hawgs, Powell-Peralta, Blood Orange, Caliber or Gullwing"

In [11]:
mkt_amazon["Category"].unique()

<StringArray>
['Sports & Outdoors | Outdoor Recreation | Skates, Skateboards & Scooters | Skateboarding | Standard Skateboards & Longboards | Longboards',
                                                                                'Toys & Games | Learning & Education | Science Kits & Toys',
                                                                                                'Toys & Games | Arts & Crafts | Craft Kits',
                                                          'Toys & Games | Hobbies | Models & Model Kits | Model Kits | Airplane & Jet Kits',
                                                                                                  'Toys & Games | Puzzles | Jigsaw Puzzles',
                                                                                                                                        nan,
                                                      'Clothing, Shoes & Jewelry | Costumes & Accessories | Kids & Baby | Girls | Costumes',
                                                                     'Toys & Games | Arts & Crafts | Drawing & Painting Supplies | Crayons',
                                                 'Home & Kitchen | Home Décor | Window Treatments | Window Stickers & Films | Window Films',
                                                                                                       'Toys & Games | Baby & Toddler Toys',
 ...
         'Clothing, Shoes & Jewelry | Shoe, Jewelry & Watch Accessories | Jewelry Accessories | Jewelry Boxes & Organizers | Jewelry Trays',
                                     'Home & Kitchen | Home Décor | Home Décor Accents | Collectible Buildings & Accessories | Accessories',
                                'Toys & Games | Collectible Toys | Collectible Display & Storage | Display Cases & Stands | Display Stands',
                                                        'Arts, Crafts & Sewing | Painting, Drawing & Art Supplies | Art Paper | Easel Pads',
                                                                                     'Arts, Crafts & Sewing | Sewing | Storage & Furniture',
                                                                                   'Cell Phones & Accessories | Accessories | Phone Charms',
                                                   'Home & Kitchen | Kitchen & Dining | Kitchen & Table Linens | Dish Cloths & Dish Towels',
 'Toys & Games | Hobbies | Remote & App Controlled Vehicles & Parts | Remote & App Controlled Vehicle Parts | Servos & Parts | Servo Gears',
                                                                                        'Electronics | Camera & Photo | Video | Camcorders',
                                                           'Clothing, Shoes & Jewelry | Novelty & More | Clothing | Novelty | Men | Shirts']
Length: 939, dtype: str